### ISSUE TITLE
Question: I'm planning to use this package

### ISSUE THREAD

**Issue by vigo** [MDziwny/django-fsm#1]
Hi, It looks that your version is the current working one for latest Django. I'm planning to use this. Will you keep maintaining the project? Thanks in advance!

**Comment by MDziwny** [comment]
Hi,

I will do my best to keep it up to date, and any help is welcomed.

FYI, I'm not planning to add new feature, I just want to keep the original django-fsm up to date with the recent versions of Django and python.

**Comment by vigo** [comment]
Thanks a lot man! I'd like to give a hand too 8)

**Comment by epalm** [comment]
I'm also planning to use this. Thanks @MDziwny for forking/maintaining! Looks complete, and as you said, just needs to be kept-up to-date with Python and Django.

Just a note, you might want to edit `README.rst` to indicate that it's available on PyPi as `django-fsa`. I had to `pip search django-fsm` and happened to find it by matching the version number ("2.7.1") you mentioned at the bottom of `README.rst`.

**Comment by vigo** [comment]
yeah! great! thanx a lot man!
